### ISSUE TITLE
Walter Music

### ISSUE THREAD

**Issue by ShyNuke3D** [AtobaAzul/UncompromisingMode#28] opened 2023-03-12 16:04 UTC
###### Description
-Not sure if a bug or not: the music plays whenever, being day, dusk or night.

###### Version
-DST Beta, UM Live.

**Comment by AtobaAzul** [comment] 2023-03-12 16:05
Personally, I'd say working as intended, but I'll wait for @Shodance to give the final word.

**Comment by AtobaAzul** [comment] 2023-03-14 16:37
Fixed indev, coming soon to live.

**Closed as completed by AtobaAzul** 2023-03-14 16:37 UTC
Labels: bug
